### ISSUE TITLE
Do not show too biq implementations in selection results

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/nisq-analyzer#15]
If prolog rules estimate, that an implementation is executable but the transpiler (qiskit-service) cannot transpile it because too many qubits are required, the "estimate" flag is false but analysedDepth and analysedWidth is 0.

Therefore, this case should not be shown in response.

**Comment by TimPhillip** [comment]
In case too many qubits are required, the Qiskit Services returns HTTP code 200, but content { "error" : "..."}.
