### ISSUE TITLE
Dockerize nisq-analyzer +  qiskit-service + qc-atlas + qc-atlas-ui + dbs (size: medium)

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/nisq-analyzer#4]
Create a docker-compose that contains nisq-analyzer and qiskit-service.

### Acceptance Criteria:
1. docker-compose containing nisq-analyzer, qiskit-service, qc-atlas-ui, qc-atlas

**Comment by FlxB2** [comment]
Resolved with [Quantil-Docker PR#2](https://github.com/UST-QuAntiL/quantil-docker/pull/2)
